
api:
  host: "0.0.0.0"
  port: 8000

# config.yml
communication:
  mqtt:
    host: "localhost"
    port: 1883
    username: "user"
    password: "pass"
  # Future communication configs
  # wifi:
  #   ssid: "network"
  #   password: "pass"

gpio:
  pins:
    bulb1:
      pin: 5
      type: "output"
      initial: false

temperature_monitor:
  database:
    path: "temperature.db"
  sensors:
    - id: "sensor1"
      bus: 1
      address: 0x48
    - id: "sensor2"
      bus: 1
      address: 0x49
  reading_interval: 60
  sync_interval: 300

logging:
  level: "INFO"
  file: "logs/iot_gateway.log"
  max_size: 10  # MB
  backup_count: 5
  format: "%(asctime)s - %(name)s - [%(levelname)s] - %(message)s"
