api:
  host: "0.0.0.0"
  port: 8000

# config.yml
communication:
  mqtt:
    host: "broker.hivemq.com"
    port: 1883
    username: "user"
    password: "pass"
    keepalive: 60
    client_id: "gateway"
    ssl: false
    reconnect_interval: 5
    max_reconnect_attempts: 5
  # Future communication configs
  # wifi:
  #   ssid: "network"
  #   password: "pass"

devices:
  bulb1:
    type: "bulb"
    pin: 5
    initial: false
  plug1:
    type: "smart_plug"
    pin: 6
    initial: false
  device3:
    type: "new_device"
    # device-specific config

# gpio:
#   pins:
#     bulb1:
#       pin: 5
#       type: "output"
#       initial: false

temperature_monitor:
  database:
    path: "temperature.db"
  i2c_bus: 1
  sensors:
    - id: "sensor1"
      bus: 1
      address: 0x48
      type: "TMP102"
    - id: "sensor2"
      bus: 1
      address: 0x49
      type: "SHT31"
  reading_interval: 60
  sync_interval: 300

logging:
  level: "INFO"
  file: "logs/iot_gateway.log"
  max_size: 10  # MB
  backup_count: 5
  format: "%(asctime)s - %(name)s - [%(levelname)s] - %(message)s"