api:
  host: "0.0.0.0"
  port: 8000

database:
  # path: "/var/lib/sensor_data/sensors.db"
  path: sensors.db
  pool_size: 5
  retention_days: 30
  db_cleanup_check_interval: 86400 # 24 hours in seconds
  vacuum_interval: 86400  # Daily vacuum for optimization

sync:
  interval: 30  # sync interval in seconds
  batch_size: 100
  error_retry_interval: 5
  cache_size: 1000
  cache_expiry: 3600
  periodic_sync: false
  protocols:
    mqtt:
      enabled: true
      batch_size: 50
      retry_interval: 300
      qos: 1
    rest:
      enabled: true
      batch_size: 20
      retry_interval: 600
      timeout: 30

# config.yml
communication:
  mqtt:
    enabled: true
    host: "broker.emqx.io"
    port: 1883
    username: "user"
    password: "pass"
    client_id: "gateway"
    keepalive: 60
    reconnect_interval: 5.0
    max_reconnect_attempts: 5
    message_queue_size: 1000
    connection_timeout: 100
    subscribe_qos: 0
    publish_qos: 0
    ssl: false
    ca_cert: "/path/to/ca.crt"  # Optional: Custom CA certificate
    client_cert: "/path/to/client.crt"  # Optional: Client certificate
    client_key: "/path/to/client.key"  # Required if client_cert is set
    tls_version: "TLS1_2"  # Optional: TLS1_2, TLS1_3, etc.
    verify_hostname: true  # Optional: Verify broker's hostname
    subscribe_topics:
      - devices/smart_plug/plug1/command
      - gateway/#
      - temperature/ack
      - temperature/sync
    
  # Future communication configs
  # wifi:
  #   enabled: true
  #   ssid: "network"
  #   password: "pass"

devices:
  bulb1:
    enabled: true
    type: "bulb"
    pin: 5
    initial: false
  plug1:
    enabled: true
    type: "smart_plug"
    pin: 6
    initial: false
  device3:
    enabled: true
    type: "new_device"
    # device-specific config

# gpio:
#   pins:
#     bulb1:
#       pin: 5
#       type: "output"
#       initial: false

system:
  device_id: "iot_gateway"
  heart_beat_interval: 60
  heart_beat_topic_prefix: "iot_gateway"

sensors:
  temperature:
    table_name: "humidity_readings"
    batch_size: 100
    max_age_days: 30
    reading_interval: 60
    i2c:
      - id: "sensor1"
        enabled: true
        bus: 1
        address: 0x48
        type: "TMP102"
        bus_number: 1  # specify which bus to use
        reading_interval: 60
        sync_interval: 300

      - id: "sensor2"
        enabled: true
        bus: 1
        address: 0x49
        type: "SHT31"
        bus_number: 2  # specify which bus to use
        reading_interval: 60
        sync_interval: 300
  
  humidity:
    table_name: "humidity_readings"
    batch_size: 100
    max_age_days: 30

      
  pressure:
    table_name: "pressure_readings"
    batch_size: 100
    max_age_days: 30

logging:
  level: "INFO"
  # level: "DEBUG"
  file: "logs/iot_gateway.log"
  max_size: 10  # MB
  backup_count: 5
  format: "%(asctime)s - %(name)s - [%(levelname)s] - %(message)s"