api:
  host: "0.0.0.0"
  port: 8000

database:
  # path: "/var/lib/sensor_data/sensors.db"
  path: sensors.db
  pool_size: 5
  vacuum_interval: 86400  # Daily vacuum for optimization

sync:
  interval: 300  # sync interval in seconds
  batch_size: 100
  error_retry_interval: 60
  cache_size: 1000
  cache_expiry: 3600
  protocols:
    mqtt:
      enabled: true
      batch_size: 50
      retry_interval: 300
      qos: 1
    rest:
      enabled: true
      batch_size: 20
      retry_interval: 600
      timeout: 30

# config.yml
communication:
  mqtt:
    host: "broker.emqx.io"
    port: 1883
    username: "user"
    password: "pass"
    client_id: "gateway"
    keepalive: 60
    reconnect_interval: 5.0
    max_reconnect_attempts: 5
    message_queue_size: 1000
    connection_timeout: 60
    subscribe_topics:
      - devices/smart_plug/plug1/command
      - gateway/#
  # Future communication configs
  # wifi:
  #   ssid: "network"
  #   password: "pass"

devices:
  bulb1:
    type: "bulb"
    pin: 5
    initial: false
  plug1:
    type: "smart_plug"
    pin: 6
    initial: false
  device3:
    type: "new_device"
    # device-specific config

# gpio:
#   pins:
#     bulb1:
#       pin: 5
#       type: "output"
#       initial: false


sensors:
  temperature:
    table_name: "humidity_readings"
    batch_size: 100
    max_age_days: 30
    reading_interval: 60
    i2c:
      - id: "sensor1"
        enabled: true
        bus: 1
        address: 0x48
        type: "TMP102"
        bus_number: 1  # specify which bus to use
        reading_interval: 60
        sync_interval: 300

      - id: "sensor2"
        enabled: true
        bus: 1
        address: 0x49
        type: "SHT31"
        bus_number: 2  # specify which bus to use
        reading_interval: 60
        sync_interval: 300
  
  humidity:
    table_name: "humidity_readings"
    batch_size: 100
    max_age_days: 30

      
  pressure:
    table_name: "pressure_readings"
    batch_size: 100
    max_age_days: 30

logging:
  level: "INFO"
  # level: "DEBUG"
  file: "logs/iot_gateway.log"
  max_size: 10  # MB
  backup_count: 5
  format: "%(asctime)s - %(name)s - [%(levelname)s] - %(message)s"